export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Posts } from "./Posts";
export { default as AskQuestion } from "./AskQuestion";
export { default as PostPage } from "./PostPage";
export { default as User } from "./User";
export { default as Users } from "./Users";
export { default as Tags } from "./Tags";
export { default as ResetPassword } from "./ResetPassword";
